/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */



define({
    dialogTitle: "Event Action Center",
    selectAllLabel: "Select All",
    applyButtonLabel: "Apply",
    emptyListText: "No Events found.",
    ToolbarItemBack: "Back",
    ToolbarItemRefresh: "Refresh",
    finishButtonLabel: "Finish",
    addRuleHeaderLabel: "Add Rule",
    ToolbarItemFilter: "Filter",
    eventPlanNameLabel: "Change in employee location",
    addActionPlan: "Add action plan",
    actionPlan: "Action plan",
    columnEventName: "Event Name",
    columnSystemName: "System Name",
    columnActionPlan: "Action Plan",
    sourceLabel: "Source",
    editButtonLabel: "Edit",
    rulesLabel: "Rules",
    editAllButtonLabel: "Edit all",
    runAs: "Run as",
    processMode: "Process mode",
    noRulesDefined: "No Rules Defined",
    noActionDefined: "No Action Defined",
    noRecordsFound: "No Records found",
    actionsRequired: "Actions are required",
    resultfromPrevAct: 'Result from previous Action',
    listViewPageEventLabel: "Event",
    editActionPlan: "Edit Action Plan",
    addNew: "Add new Action plan",
    action: "Action Plan",
    addActionSummaryPageActionPlanLabel: "Action Plan",
    addActionSummaryPageBusinessApplication: "Business application",
    addActionSummaryPageEvent: "Event",
    backButtonLabel: "Back",
    nextButtonLabel: "Next",
    listViewPageAddActionPlan: "+ Add Action plan",
    listViewPageViewActionPlan: " Action plan",
    addActionSummaryPageRulesLabel: "Rules",
    actionPlanLabel: "Action Label",
    editRuleHeaderLabel: "Edit Rules",
    addActionPlanLabel: "Add Action Plan",
    editActionPlanLabel: "Edit Action Plan",
    saveActionPlanLabel: "Save Action Plan",
    updateActionPlanLabel: "Update Action Plan",
    addRuleDialogTitle: "Add Rule ",
    bussapplicatoin: "Business application",
    ruleLabel: "Rule",
    conditionLabel:"Condition",
    warningMsgondeletionOfLast1Rule: "Atleast 1 empty rule is mandatory",
    warningMsgondeletionOfLast1Action: "Atleast 1 Action is mandatory",
    confirmDeleteMsg: "Are you sure you want to delete the Action?",
    conjunctionAndLabel: "And",
    conjunctionOrLabel: "Or",
    operatorEqualtoLabel: "Equal to",
    operatorNotequaltoLabel: "Not equal to",
    synchronouslyProcessLabel: "Synchronously",
    csObjLabel: "Content Server object",
    evtPropLabel: "Event property",
    prevActLabel: "Result from previous action",
    actionLabel: "Action"
});
